/**
 * Ports (legacy PORTS): the UN/LOCODEs the office ships from and to, with their name and
 * country. Seed for the `ports` Settings table; the running app reads the table. A port typed
 * that is not in the table is still accepted — the table suggests, it does not restrict.
 */
export type Port = { code: string; name: string; country: string };

export const DEFAULT_PORTS: Port[] = [
  { code: "BEANR", name: "Antwerp", country: "BE" },
  { code: "BEZEE", name: "Zeebrugge", country: "BE" },
  { code: "BEGNE", name: "Ghent", country: "BE" },
  { code: "NLRTM", name: "Rotterdam", country: "NL" },
  { code: "NLAMS", name: "Amsterdam", country: "NL" },
  { code: "NLVLI", name: "Vlissingen", country: "NL" },
  { code: "DEHAM", name: "Hamburg", country: "DE" },
  { code: "DEBRV", name: "Bremerhaven", country: "DE" },
  { code: "DEWVN", name: "Wilhelmshaven", country: "DE" },
  { code: "FRLEH", name: "Le Havre", country: "FR" },
  { code: "FRDKK", name: "Dunkirk", country: "FR" },
  { code: "FRRON", name: "Rouen", country: "FR" },
  { code: "GBFXT", name: "Felixstowe", country: "GB" },
  { code: "GBLGP", name: "London Gateway", country: "GB" },
  { code: "GBSOU", name: "Southampton", country: "GB" },
  { code: "GBLIV", name: "Liverpool", country: "GB" },
  { code: "GBTEE", name: "Teesport", country: "GB" },
  { code: "GBGRG", name: "Grangemouth", country: "GB" },
  { code: "IEDUB", name: "Dublin", country: "IE" },
  { code: "IEORK", name: "Cork", country: "IE" },
  { code: "PLGDN", name: "Gdansk", country: "PL" },
  { code: "PLGDY", name: "Gdynia", country: "PL" },
  { code: "LTKLJ", name: "Klaipeda", country: "LT" },
  { code: "LVRIX", name: "Riga", country: "LV" },
  { code: "EETLL", name: "Tallinn", country: "EE" },
  { code: "FIHEL", name: "Helsinki", country: "FI" },
  { code: "FIKTK", name: "Kotka", country: "FI" },
  { code: "SEGOT", name: "Gothenburg", country: "SE" },
  { code: "SEHEL", name: "Helsingborg", country: "SE" },
  { code: "DKAAR", name: "Aarhus", country: "DK" },
  { code: "DKCPH", name: "Copenhagen", country: "DK" },
  { code: "NOOSL", name: "Oslo", country: "NO" },
  { code: "RULED", name: "St Petersburg", country: "RU" },
  { code: "RUKGD", name: "Kaliningrad", country: "RU" },
  { code: "ESVLC", name: "Valencia", country: "ES" },
  { code: "ESALG", name: "Algeciras", country: "ES" },
  { code: "ESBCN", name: "Barcelona", country: "ES" },
  { code: "ESBIO", name: "Bilbao", country: "ES" },
  { code: "ESLPA", name: "Las Palmas", country: "ES" },
  { code: "ESTCI", name: "Tenerife", country: "ES" },
  { code: "PTLIS", name: "Lisbon", country: "PT" },
  { code: "PTLEI", name: "Leixoes", country: "PT" },
  { code: "PTSIE", name: "Sines", country: "PT" },
  { code: "FRFOS", name: "Fos-sur-Mer", country: "FR" },
  { code: "FRMRS", name: "Marseille", country: "FR" },
  { code: "ITGOA", name: "Genoa", country: "IT" },
  { code: "ITSPE", name: "La Spezia", country: "IT" },
  { code: "ITLIV", name: "Livorno", country: "IT" },
  { code: "ITGIT", name: "Gioia Tauro", country: "IT" },
  { code: "ITNAP", name: "Naples", country: "IT" },
  { code: "ITSAL", name: "Salerno", country: "IT" },
  { code: "ITTRS", name: "Trieste", country: "IT" },
  { code: "ITVCE", name: "Venice", country: "IT" },
  { code: "ITRAN", name: "Ravenna", country: "IT" },
  { code: "MTMAR", name: "Marsaxlokk", country: "MT" },
  { code: "SIKOP", name: "Koper", country: "SI" },
  { code: "HRRJK", name: "Rijeka", country: "HR" },
  { code: "GRPIR", name: "Piraeus", country: "GR" },
  { code: "GRSKG", name: "Thessaloniki", country: "GR" },
  { code: "CYLMS", name: "Limassol", country: "CY" },
  { code: "TRIST", name: "Istanbul (Ambarli)", country: "TR" },
  { code: "TRIZM", name: "Izmir", country: "TR" },
  { code: "TRALI", name: "Aliaga", country: "TR" },
  { code: "TRGEM", name: "Gemlik", country: "TR" },
  { code: "TRMER", name: "Mersin", country: "TR" },
  { code: "TRISK", name: "Iskenderun", country: "TR" },
  { code: "TRTEK", name: "Tekirdag", country: "TR" },
  { code: "TRSSX", name: "Samsun", country: "TR" },
  { code: "ROCND", name: "Constanta", country: "RO" },
  { code: "BGVAR", name: "Varna", country: "BG" },
  { code: "BGBOJ", name: "Burgas", country: "BG" },
  { code: "UAODS", name: "Odessa", country: "UA" },
  { code: "GEPTI", name: "Poti", country: "GE" },
  { code: "GEBUS", name: "Batumi", country: "GE" },
  { code: "LBBEY", name: "Beirut", country: "LB" },
  { code: "SYLTK", name: "Lattakia", country: "SY" },
  { code: "SYTTS", name: "Tartus", country: "SY" },
  { code: "ILHFA", name: "Haifa", country: "IL" },
  { code: "ILASH", name: "Ashdod", country: "IL" },
  { code: "JOAQJ", name: "Aqaba", country: "JO" },
  { code: "MACAS", name: "Casablanca", country: "MA" },
  { code: "MATNG", name: "Tanger Med", country: "MA" },
  { code: "MAAGA", name: "Agadir", country: "MA" },
  { code: "DZALG", name: "Algiers", country: "DZ" },
  { code: "DZORN", name: "Oran", country: "DZ" },
  { code: "DZAAE", name: "Annaba", country: "DZ" },
  { code: "TNTUN", name: "Tunis (Rades)", country: "TN" },
  { code: "TNSFA", name: "Sfax", country: "TN" },
  { code: "TNSUS", name: "Sousse", country: "TN" },
  { code: "LYTIP", name: "Tripoli", country: "LY" },
  { code: "LYBEN", name: "Benghazi", country: "LY" },
  { code: "LYMRA", name: "Misurata", country: "LY" },
  { code: "LYKHO", name: "Khoms", country: "LY" },
  { code: "EGALY", name: "Alexandria", country: "EG" },
  { code: "EGPSD", name: "Port Said", country: "EG" },
  { code: "EGSOK", name: "Sokhna", country: "EG" },
  { code: "EGDAM", name: "Damietta", country: "EG" },
  { code: "EGEDK", name: "Dekheila", country: "EG" },
  { code: "SNDKR", name: "Dakar", country: "SN" },
  { code: "MRNKC", name: "Nouakchott", country: "MR" },
  { code: "GMBJL", name: "Banjul", country: "GM" },
  { code: "GNCKY", name: "Conakry", country: "GN" },
  { code: "SLFNA", name: "Freetown", country: "SL" },
  { code: "LRMLW", name: "Monrovia", country: "LR" },
  { code: "CIABJ", name: "Abidjan", country: "CI" },
  { code: "CISPY", name: "San Pedro", country: "CI" },
  { code: "GHTEM", name: "Tema", country: "GH" },
  { code: "GHTKD", name: "Takoradi", country: "GH" },
  { code: "TGLFW", name: "Lome", country: "TG" },
  { code: "BJCOO", name: "Cotonou", country: "BJ" },
  { code: "NGLOS", name: "Lagos (Apapa)", country: "NG" },
  { code: "NGTIN", name: "Lagos (Tin Can)", country: "NG" },
  { code: "NGONN", name: "Onne", country: "NG" },
  { code: "NGCBQ", name: "Calabar", country: "NG" },
  { code: "CMDLA", name: "Douala", country: "CM" },
  { code: "CMKBI", name: "Kribi", country: "CM" },
  { code: "GQSSG", name: "Malabo", country: "GQ" },
  { code: "GQBSG", name: "Bata", country: "GQ" },
  { code: "GALBV", name: "Libreville", country: "GA" },
  { code: "GAPOG", name: "Port-Gentil", country: "GA" },
  { code: "GAOWE", name: "Owendo", country: "GA" },
  { code: "CGPNR", name: "Pointe-Noire", country: "CG" },
  { code: "CDMAT", name: "Matadi", country: "CD" },
  { code: "CDBOA", name: "Boma", country: "CD" },
  { code: "AOLAD", name: "Luanda", country: "AO" },
  { code: "AOLOB", name: "Lobito", country: "AO" },
  { code: "AONAM", name: "Namibe", country: "AO" },
  { code: "NAWVB", name: "Walvis Bay", country: "NA" },
  { code: "ZACPT", name: "Cape Town", country: "ZA" },
  { code: "ZAPLZ", name: "Port Elizabeth", country: "ZA" },
  { code: "ZAZBA", name: "Ngqura (Coega)", country: "ZA" },
  { code: "ZADUR", name: "Durban", country: "ZA" },
  { code: "MZMPM", name: "Maputo", country: "MZ" },
  { code: "MZBEW", name: "Beira", country: "MZ" },
  { code: "MZUEL", name: "Nacala", country: "MZ" },
  { code: "MGTMM", name: "Toamasina", country: "MG" },
  { code: "MUPLU", name: "Port Louis", country: "MU" },
  { code: "TZDAR", name: "Dar es Salaam", country: "TZ" },
  { code: "KEMBA", name: "Mombasa", country: "KE" },
  { code: "DJJIB", name: "Djibouti", country: "DJ" },
  { code: "SDPZU", name: "Port Sudan", country: "SD" },
  { code: "SOMGQ", name: "Mogadishu", country: "SO" },
  { code: "SAJED", name: "Jeddah", country: "SA" },
  { code: "SADMM", name: "Dammam", country: "SA" },
  { code: "SAJUB", name: "Jubail", country: "SA" },
  { code: "SAKAC", name: "King Abdullah Port", country: "SA" },
  { code: "YEHOD", name: "Hodeidah", country: "YE" },
  { code: "YEADE", name: "Aden", country: "YE" },
  { code: "AEJEA", name: "Jebel Ali", country: "AE" },
  { code: "AESHJ", name: "Sharjah", country: "AE" },
  { code: "AEKLF", name: "Khalifa (Abu Dhabi)", country: "AE" },
  { code: "AEAJM", name: "Ajman", country: "AE" },
  { code: "AEFJR", name: "Fujairah", country: "AE" },
  { code: "OMSLL", name: "Salalah", country: "OM" },
  { code: "OMSOH", name: "Sohar", country: "OM" },
  { code: "OMMCT", name: "Muscat", country: "OM" },
  { code: "QAHMD", name: "Hamad", country: "QA" },
  { code: "BHKBS", name: "Khalifa Bin Salman", country: "BH" },
  { code: "KWSWK", name: "Shuwaikh", country: "KW" },
  { code: "KWSAA", name: "Shuaiba", country: "KW" },
  { code: "IQUQR", name: "Umm Qasr", country: "IQ" },
  { code: "IRBND", name: "Bandar Abbas", country: "IR" },
  { code: "IRBUZ", name: "Bushehr", country: "IR" },
  { code: "PKKHI", name: "Karachi", country: "PK" },
  { code: "PKQCT", name: "Port Qasim", country: "PK" },
  { code: "PKGWD", name: "Gwadar", country: "PK" },
  { code: "INMUN", name: "Mundra", country: "IN" },
  { code: "INNSA", name: "Nhava Sheva (JNPT)", country: "IN" },
  { code: "INBOM", name: "Mumbai", country: "IN" },
  { code: "INHZR", name: "Hazira", country: "IN" },
  { code: "INPAV", name: "Pipavav", country: "IN" },
  { code: "INIXY", name: "Kandla", country: "IN" },
  { code: "INMAA", name: "Chennai", country: "IN" },
  { code: "INENR", name: "Ennore (Kamarajar)", country: "IN" },
  { code: "INTUT", name: "Tuticorin", country: "IN" },
  { code: "INCOK", name: "Cochin", country: "IN" },
  { code: "INVTZ", name: "Visakhapatnam", country: "IN" },
  { code: "INCCU", name: "Kolkata", country: "IN" },
  { code: "INHAL", name: "Haldia", country: "IN" },
  { code: "INKRI", name: "Krishnapatnam", country: "IN" },
  { code: "LKCMB", name: "Colombo", country: "LK" },
  { code: "BDCGP", name: "Chittagong", country: "BD" },
  { code: "BDMGL", name: "Mongla", country: "BD" },
  { code: "MVMLE", name: "Male", country: "MV" },
  { code: "SGSIN", name: "Singapore", country: "SG" },
  { code: "MYPKG", name: "Port Klang", country: "MY" },
  { code: "MYTPP", name: "Tanjung Pelepas", country: "MY" },
  { code: "MYPEN", name: "Penang", country: "MY" },
  { code: "MYBTU", name: "Bintulu", country: "MY" },
  { code: "MYKCH", name: "Kuching", country: "MY" },
  { code: "THLCH", name: "Laem Chabang", country: "TH" },
  { code: "THBKK", name: "Bangkok", country: "TH" },
  { code: "VNSGN", name: "Ho Chi Minh City", country: "VN" },
  { code: "VNCLI", name: "Cai Mep", country: "VN" },
  { code: "VNHPH", name: "Haiphong", country: "VN" },
  { code: "VNDAD", name: "Da Nang", country: "VN" },
  { code: "IDJKT", name: "Jakarta (Tanjung Priok)", country: "ID" },
  { code: "IDSUB", name: "Surabaya", country: "ID" },
  { code: "IDBLW", name: "Belawan", country: "ID" },
  { code: "IDSRG", name: "Semarang", country: "ID" },
  { code: "PHMNL", name: "Manila", country: "PH" },
  { code: "PHCEB", name: "Cebu", country: "PH" },
  { code: "KHSIH", name: "Sihanoukville", country: "KH" },
  { code: "MMRGN", name: "Yangon", country: "MM" },
  { code: "BNMUA", name: "Muara", country: "BN" },
  { code: "CNSHA", name: "Shanghai", country: "CN" },
  { code: "CNNGB", name: "Ningbo", country: "CN" },
  { code: "CNSZX", name: "Shenzhen", country: "CN" },
  { code: "CNYTN", name: "Yantian", country: "CN" },
  { code: "CNCAN", name: "Guangzhou", country: "CN" },
  { code: "CNHUA", name: "Huangpu", country: "CN" },
  { code: "CNTAO", name: "Qingdao", country: "CN" },
  { code: "CNTXG", name: "Tianjin", country: "CN" },
  { code: "CNDLC", name: "Dalian", country: "CN" },
  { code: "CNXMN", name: "Xiamen", country: "CN" },
  { code: "CNFOC", name: "Fuzhou", country: "CN" },
  { code: "CNLYG", name: "Lianyungang", country: "CN" },
  { code: "CNSWA", name: "Shantou", country: "CN" },
  { code: "CNZHA", name: "Zhanjiang", country: "CN" },
  { code: "CNNKG", name: "Nanjing", country: "CN" },
  { code: "HKHKG", name: "Hong Kong", country: "HK" },
  { code: "TWKHH", name: "Kaohsiung", country: "TW" },
  { code: "TWKEL", name: "Keelung", country: "TW" },
  { code: "TWTXG", name: "Taichung", country: "TW" },
  { code: "KRPUS", name: "Busan", country: "KR" },
  { code: "KRINC", name: "Incheon", country: "KR" },
  { code: "KRKAN", name: "Gwangyang", country: "KR" },
  { code: "JPTYO", name: "Tokyo", country: "JP" },
  { code: "JPYOK", name: "Yokohama", country: "JP" },
  { code: "JPUKB", name: "Kobe", country: "JP" },
  { code: "JPNGO", name: "Nagoya", country: "JP" },
  { code: "JPOSA", name: "Osaka", country: "JP" },
  { code: "JPHKT", name: "Hakata", country: "JP" },
  { code: "USNYC", name: "New York / New Jersey", country: "US" },
  { code: "USBAL", name: "Baltimore", country: "US" },
  { code: "USORF", name: "Norfolk", country: "US" },
  { code: "USCHS", name: "Charleston", country: "US" },
  { code: "USSAV", name: "Savannah", country: "US" },
  { code: "USJAX", name: "Jacksonville", country: "US" },
  { code: "USMIA", name: "Miami", country: "US" },
  { code: "USPEF", name: "Port Everglades", country: "US" },
  { code: "USHOU", name: "Houston", country: "US" },
  { code: "USNOL", name: "New Orleans", country: "US" },
  { code: "USMOB", name: "Mobile", country: "US" },
  { code: "USLAX", name: "Los Angeles", country: "US" },
  { code: "USLGB", name: "Long Beach", country: "US" },
  { code: "USOAK", name: "Oakland", country: "US" },
  { code: "USSEA", name: "Seattle", country: "US" },
  { code: "USTIW", name: "Tacoma", country: "US" },
  { code: "USPDX", name: "Portland", country: "US" },
  { code: "CAMTR", name: "Montreal", country: "CA" },
  { code: "CAHAL", name: "Halifax", country: "CA" },
  { code: "CAVAN", name: "Vancouver", country: "CA" },
  { code: "CAPRR", name: "Prince Rupert", country: "CA" },
  { code: "MXVER", name: "Veracruz", country: "MX" },
  { code: "MXATM", name: "Altamira", country: "MX" },
  { code: "MXZLO", name: "Manzanillo", country: "MX" },
  { code: "MXLZC", name: "Lazaro Cardenas", country: "MX" },
  { code: "MXESE", name: "Ensenada", country: "MX" },
  { code: "PABLB", name: "Balboa", country: "PA" },
  { code: "PACRI", name: "Cristobal", country: "PA" },
  { code: "PAMIT", name: "Manzanillo (Colon)", country: "PA" },
  { code: "CRLIO", name: "Puerto Limon", country: "CR" },
  { code: "CRCAL", name: "Caldera", country: "CR" },
  { code: "GTSTC", name: "Santo Tomas de Castilla", country: "GT" },
  { code: "GTQUE", name: "Puerto Quetzal", country: "GT" },
  { code: "HNPCR", name: "Puerto Cortes", country: "HN" },
  { code: "NIICI", name: "Corinto", country: "NI" },
  { code: "SVAQJ", name: "Acajutla", country: "SV" },
  { code: "DOCAU", name: "Caucedo", country: "DO" },
  { code: "DOHAI", name: "Rio Haina", country: "DO" },
  { code: "JMKIN", name: "Kingston", country: "JM" },
  { code: "HTPAP", name: "Port-au-Prince", country: "HT" },
  { code: "TTPOS", name: "Port of Spain", country: "TT" },
  { code: "BSFPO", name: "Freeport", country: "BS" },
  { code: "CUHAV", name: "Havana", country: "CU" },
  { code: "COCTG", name: "Cartagena", country: "CO" },
  { code: "COBUN", name: "Buenaventura", country: "CO" },
  { code: "COBAQ", name: "Barranquilla", country: "CO" },
  { code: "VELAG", name: "La Guaira", country: "VE" },
  { code: "VEPBL", name: "Puerto Cabello", country: "VE" },
  { code: "ECGYE", name: "Guayaquil", country: "EC" },
  { code: "ECPBO", name: "Posorja", country: "EC" },
  { code: "PECLL", name: "Callao", country: "PE" },
  { code: "PEPAI", name: "Paita", country: "PE" },
  { code: "CLVAP", name: "Valparaiso", country: "CL" },
  { code: "CLSAI", name: "San Antonio", country: "CL" },
  { code: "CLSVE", name: "San Vicente", country: "CL" },
  { code: "BRSSZ", name: "Santos", country: "BR" },
  { code: "BRRIO", name: "Rio de Janeiro", country: "BR" },
  { code: "BRPNG", name: "Paranagua", country: "BR" },
  { code: "BRITJ", name: "Itajai", country: "BR" },
  { code: "BRNVT", name: "Navegantes", country: "BR" },
  { code: "BRRIG", name: "Rio Grande", country: "BR" },
  { code: "BRSUA", name: "Suape", country: "BR" },
  { code: "BRSSA", name: "Salvador", country: "BR" },
  { code: "BRVIX", name: "Vitoria", country: "BR" },
  { code: "BRMAO", name: "Manaus", country: "BR" },
  { code: "BRPEC", name: "Pecem", country: "BR" },
  { code: "ARBUE", name: "Buenos Aires", country: "AR" },
  { code: "ARZAE", name: "Zarate", country: "AR" },
  { code: "UYMVD", name: "Montevideo", country: "UY" },
  { code: "PYASU", name: "Asuncion", country: "PY" },
];

export const PORT_CODE = /^[A-Z]{2}[A-Z2-9]{3}$/;

/**
 * The editor's text: one port per line as `CODE Name CC` (the country last). Blank lines are
 * dropped, a code twice keeps its first line, and a bad line is reported by number.
 */
export function parsePortLines(text: string): { ports: Port[]; problems: string[] } {
  const ports: Port[] = [];
  const problems: string[] = [];
  const seen = new Set<string>();
  text.split(/\r?\n/).forEach((raw, i) => {
    const line = raw.trim();
    if (!line) return;
    const m = /^([A-Za-z0-9]{5})\s+(.+?)\s+([A-Za-z]{2})$/.exec(line);
    if (!m || !PORT_CODE.test(m[1].toUpperCase())) {
      problems.push(`Line ${i + 1}: expected "CODE Name CC", e.g. BEANR Antwerp BE`);
      return;
    }
    const code = m[1].toUpperCase();
    if (seen.has(code)) return;
    seen.add(code);
    ports.push({ code, name: m[2].trim(), country: m[3].toUpperCase() });
  });
  return { ports, problems };
}

export const portLines = (ports: readonly Port[]) =>
  ports.map((p) => `${p.code} ${p.name} ${p.country}`).join("\n");
