import { date, index, pgTable, text, uuid } from "drizzle-orm/pg-core";
import { recordColumns } from "./_columns";
import { activityStateEnum, roleEnum } from "./enums";
import { users } from "./identity";

/**
 * Tasks, generated by document rules or by hand. A rule names a role; the person is resolved
 * when it fires (invariant 3). Withdrawn with a reason, never deleted.
 */
export const activities = pgTable(
  "activities",
  {
    ...recordColumns,
    title: text().notNull(),
    assigneeId: uuid().references(() => users.id),
    role: roleEnum(),
    due: date({ mode: "string" }),
    ruleCode: text(),
    state: activityStateEnum().notNull().default("open"),
    withdrawReason: text(),
    linkKind: text(),
    linkId: uuid(),
  },
  (t) => [
    index("activities_assignee_idx").on(t.assigneeId, t.state),
    index("activities_link_idx").on(t.linkKind, t.linkId),
  ],
);
