import { boolean, date, index, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";
import { recordColumns } from "./_columns";
import { activityStateEnum, roleEnum } from "./enums";
import { users } from "./identity";

/**
 * Tasks, generated by document rules or by hand. A rule names a role; the person is resolved
 * when it fires (invariant 3). Withdrawn with a reason, never deleted.
 */
export const activities = pgTable(
  "activities",
  {
    ...recordColumns,
    title: text().notNull(),
    assigneeId: uuid().references(() => users.id),
    role: roleEnum(),
    due: date({ mode: "string" }),
    ruleCode: text(),
    blocking: boolean().notNull().default(false),
    state: activityStateEnum().notNull().default("open"),
    withdrawReason: text(),
    note: text(),
    doneAt: timestamp({ withTimezone: true }),
    doneBy: uuid().references(() => users.id),
    linkKind: text(),
    linkId: uuid(),
  },
  (t) => [
    index("activities_assignee_idx").on(t.assigneeId, t.state),
    index("activities_link_idx").on(t.linkKind, t.linkId),
    index("activities_role_idx").on(t.role, t.state),
    index("activities_due_idx").on(t.due),
  ],
);

/**
 * Somebody away and who covers (domain/cover): for those days the absent person's tasks show in
 * the cover's list; nothing moves. `endedAt` ends it early ("back now") — kept, never deleted.
 */
export const covers = pgTable(
  "covers",
  {
    ...recordColumns,
    absentId: uuid()
      .notNull()
      .references(() => users.id),
    coverId: uuid()
      .notNull()
      .references(() => users.id),
    fromDate: date({ mode: "string" }).notNull(),
    toDate: date({ mode: "string" }),
    endedAt: timestamp({ withTimezone: true }),
  },
  (t) => [index("covers_cover_idx").on(t.coverId), index("covers_absent_idx").on(t.absentId)],
);
