/** A few legacy RATE_ITEMS for `db:seed -- --demo` (test material, never the real office). */
const eur = (n: number) => n * 100;

export const DEMO_RATE_ITEMS = [
  {
    category: "ocean",
    pol: "BEANR",
    pod: "CMDLA",
    country: "CM",
    containerType: "40HC",
    carrier: "MSC",
    transitDays: 22,
    sellCents: eur(4250),
    buyCents: eur(2650),
    validUntil: "2026-12-31",
  },
  {
    category: "ocean",
    pol: "BEANR",
    pod: "GALBV",
    country: "GA",
    containerType: "40HC",
    carrier: "MSC",
    transitDays: 28,
    sellCents: eur(4200),
    buyCents: eur(2445),
    validUntil: "2026-12-31",
  },
  {
    category: "ocean",
    pol: "BEANR",
    pod: "SNDKR",
    country: "SN",
    containerType: "40HC",
    carrier: "MSC",
    transitDays: 14,
    sellCents: eur(2150),
    buyCents: eur(1560),
    validUntil: "2026-11-30",
  },
  {
    category: "ocean",
    pol: "BEANR",
    pod: "TRMER",
    country: "TR",
    containerType: "40HC",
    carrier: "CMA CGM",
    transitDays: 12,
    sellCents: eur(1900),
    buyCents: eur(1300),
    rateType: "spot" as const,
  },
  {
    category: "inland",
    fromPlace: "Antwerp depot",
    toPlace: "Rumst (2840)",
    containerType: "40HC",
    carrier: "VRD Transport",
    sellCents: eur(340),
    buyCents: eur(190),
  },
  {
    category: "docs",
    docCode: "BESC",
    country: "CM",
    sellCents: eur(250),
    buyCents: eur(140),
    note: "Mandatory for Cameroon",
  },
  {
    category: "customs",
    name: "Export customs + declaration",
    sellCents: eur(300),
    buyCents: eur(145),
  },
  { category: "vgm", name: "VGM / Certiweight", sellCents: eur(120), buyCents: eur(60) },
  {
    category: "freetime",
    name: "Demurrage at destination",
    freeDays: 14,
    sellCents: eur(65),
    buyCents: eur(45),
    note: "Daily rate after the free days",
  },
  {
    category: "other",
    name: "Terminal Handling Charge (THC)",
    sellCents: eur(210),
    buyCents: eur(130),
  },
];
